services:
  fgg:
    container_name: fgg-service
    build:
      context: .
      dockerfile: Dockerfile
    image: fgg-service:latest
    ports:
      - "8181:8181"
    restart: unless-stopped
    volumes:
      - ./FGG.db:/app/FGG.db
