services:
  fgg:
    container_name: fgg-service
    build:
      context: .
      dockerfile: Dockerfile
    image: fgg-service
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./data:/app/data
