generator:
  features:
    disable:
      - "paths/client"
      - "ogen/otel"
      - "webhooks/client"
      - "client/security/reentrant"
      - "client/request/validation"
      - "ogen/unimplemented"
parser:
  infer_types: true
  allow_remote: true
  depth_limit: 1000